### PR TITLE
added solve-linear-equations

### PR DESCRIPTION
**Pull request by mehradans92**

### CODE REVIEW

**Comment by mehradans92** [comment]
Any ideas why this is failing @whitead?

**Comment by hockyg** [comment]
I'm looking at it - i don't understand the error, but I can see that it would need sympy to run your test

**Comment by mehradans92** [comment]
@hockyg Thanks for your reply. Can we add a pip install for `simpy` in the github CI?

**Comment by hockyg** [comment]
> @hockyg Thanks for your reply. Can we add a pip install for `simpy` in the github CI?

I believe @whitead says you can just add it to the requirements file and then push again

**Comment by mehradans92** [comment]
@hockyg fails also with `sympy` install. Maybe the context `sympy` undefined in the txt file?

**Comment by hockyg** [comment]
Ah yes, that is the problem. You can change to python and add 'using sympy'
to the prompt if you want. Or andrew would probably suggest that you add a
sympy context by PR in nlcc

**Review by SamCox822 — CHANGES_REQUESTED** [review]
The folder name needs to match the file names. (sle instead of solve_linear_equations)

**Comment by mehradans92** [comment]
@SamCox822 I am not sure about that. Have a look at:
https://github.com/ur-whitelab/nlcc-data/tree/main/data/derivative-simple

**Review by SamCox822 — APPROVED** [review]
Looks good :)

**Pull request merged**
