### PR TITLE
compute force constant

### PR DESCRIPTION
**Pull request by geemi725**

### CODE REVIEW

**Review by navneeth3005 — APPROVED** [review]

**Comment by whitead** [comment]
@geemi725 Can you send me the reference/textbook you used to develop this prompt? Thanks!

**Comment by geemi725** [comment]
@whitead  I am not sure which one exactly but this is one reference I used. http://openmopac.net/manual/vibrational_frequencies.html

**Comment by geemi725** [comment]
https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Spectroscopy/Vibrational_Spectroscopy/Infrared_Spectroscopy/Infrared%3A_Interpretation

**Comment by whitead** [comment]
@geemi725 which specific equation number?

**Comment by geemi725** [comment]
Equation 4 in the second link @whitead

**Pull request merged**
